export const STEP_TYPES = {
  INIT: 'INIT',
  ROUND_START: 'ROUND_START',
  EVALUATE: 'EVALUATE',
  SELECT: 'SELECT',
  UPDATE_BEST: 'UPDATE_BEST',
  NO_PROGRESS: 'NO_PROGRESS',
  FINISH: 'FINISH',
};