export const STEP_TYPES = {
  INIT: 'INIT',
  ROUND_START: 'ROUND_START',
  EVALUATE: 'EVALUATE',
  IMPROVE: 'IMPROVE',
  ROUND_SUMMARY: 'ROUND_SUMMARY',
  SELECT: 'SELECT',
  SWAP: 'SWAP',
  COVER_UPDATE: 'COVER_UPDATE',
  NO_PROGRESS: 'NO_PROGRESS',
  FINISH: 'FINISH',
};